name: "publish"

on:
  workflow_dispatch:
  push:
    branches: [main]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  BIN_PATH: clippy-bin
  DEB_PKG_NAME: clippy_1.2.1_amd64.deb
  DEB_PKG_RENAMED: clippy-1.2.1-x86_64.deb
  ARCH_PKG_NAME: clippy-bin-1.2.1-1-x86_64.pkg.tar.zst
  PACKAGE_VERSION: 1.2.1

jobs:
  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}


      - name: Create PKGBUILD & copy deb package
        run: |
          mkdir ${{ env.BIN_PATH }}
          cp -fr ${{ env.DEB_PKG_NAME }} ${{ env.BIN_PATH }}/${{ env.DEB_PKG_RENAMED }}
          cat <<EOF > ./${{ env.BIN_PATH }}/PKGBUILD
            # Maintainer: Romain Gallet <rgallet@grumlimited.co.uk>
            # Contributor: Romain Gallet <rgallet@grumlimited.co.uk>
            _packager="Romain Gallet <rgallet@grumlimited.co.uk>"
            _deb_pkgname=clippy
            pkgname=clippy-bin
            pkgver=${{ env.PACKAGE_VERSION }}
            md5sums=('$(md5sum ${{ env.BIN_PATH }}/${{ env.DEB_PKG_NAME }} | awk '{print $1}')')
            pkgrel=1
            pkgdesc='Kinesis tail tool'
            arch=('x86_64')
            url="https://github.com/don-cryptus/kinesis-tailr"
            license=('GPLv3')
            source=("$url/releases/download/0.5.7/kinesis-tailr-0.5.7-x86_64.deb")

            build() {
                rm control.tar.gz
                tar xvf data.tar.gz
            }

            package() {
                cp -fr usr/ \${pkgdir}
            }
          
          EOF
          echo ${{ env.BIN_PATH }}
          ls -a -l ${{ env.BIN_PATH }}/
          echo "----------------------"
          echo "----------------------"
          ls -a 
          echo "----------------------"
          echo "----------------------"
          cat ${{ env.BIN_PATH }}/PKGBUILD

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: 2m/arch-pkgbuild-builder@v1.17
        with:
          debug: true
          target: pkgbuild
          pkgname: ${{ env.BIN_PATH }}/

      - name: Create arch package checksum file
        run: |
          md5sum ${{ env.BIN_PATH }}/${{ env.ARCH_PKG_NAME}} >> ${{ env.BIN_PATH }}/${{ env.ARCH_PKG_NAME }}.md5sum

      - name: Upload Arch Linux release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.PACKAGE_VERSION }}
          files: |
            ${{ env.BIN_PATH }}/${{ env.ARCH_PKG_NAME }}
            ${{ env.BIN_PATH }}/${{ env.ARCH_PKG_NAME }}.md5sum

      - name: ls & cat
        run: |
          echo ${{ env.BIN_PATH }}
          ls -a -l ${{ env.BIN_PATH }}/
          echo "----------------------"
          echo "----------------------"
          ls -a 
          echo "----------------------"
          echo "----------------------"
          cat ${{ env.BIN_PATH }}/PKGBUILD
