name: "publish"

on:
  workflow_dispatch:
  push:
    branches: [main]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  DEB_PKG_NAME: kinesis-tailr-0.5.7-x86_64.deb
  RPM_PKG_NAME: kinesis-tailr-0.5.7-1.x86_64.rpm
  ARCH_PKG_NAME: kinesis-tailr-bin-0.5.7-1-x86_64.pkg.tar.zst
  PACKAGE_NAME: kinesis-tailr
  PACKAGE_VERSION: 0.5.7

jobs:
  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Upload Debian release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./${{ env.DEB_PKG_NAME }}
          tag_name: ${{ env.PACKAGE_VERSION }}

      - name: Prepare arch package metadata
        run: |
          wget https://github.com/don-cryptus/kinesis-tailr/releases/download/${{ env.PACKAGE_VERSION }}/${DEB_PKG_NAME} -O build-aux/arch/kinesis-tailr-bin/${DEB_PKG_NAME}

          MD5_SUM=$(md5sum build-aux/arch/kinesis-tailr-bin/${DEB_PKG_NAME}  | awk '{print $1}')
          awk -v q="'" -v MD5_SUM=$MD5_SUM -i inplace 'BEGINFILE{print "md5sums=(" q MD5_SUM q ")"}{print}' build-aux/arch/kinesis-tailr-bin/PKGBUILD
          awk -i inplace 'BEGINFILE{print "pkgver=${{ env.PACKAGE_VERSION }}"}{print}' build-aux/arch/kinesis-tailr-bin/PKGBUILD

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          debug: true
          target: pkgbuild
          pkgname: build-aux/arch/kinesis-tailr-bin/

      - name: Create arch package checksum file
        run: |
          sudo chown -R $USER .
          md5sum build-aux/arch/kinesis-tailr-bin/${ARCH_PKG_NAME} >> build-aux/arch/kinesis-tailr-bin/${ARCH_PKG_NAME}.md5sum

      - name: Upload Arch Linux release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.PACKAGE_VERSION }}
          files: |
            build-aux/arch/kinesis-tailr-bin/${{ env.ARCH_PKG_NAME }}
            build-aux/arch/kinesis-tailr-bin/${{ env.ARCH_PKG_NAME }}.md5sum
