name: "publish"

on:
  workflow_dispatch:
  push:
    branches: [main]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  EMAIL: don.cryptus@gmail.com
  ARCH: x86_64

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.get-package.outputs.name }}
      version: ${{ steps.get-package.outputs.version }}
      description: ${{ steps.get-package.outputs.description }}
      license: ${{ steps.get-package.outputs.license }}

    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: get package info
        id: get-package
        run: |
          echo "name=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
          echo "description=$(node -p "require('./package.json').description")" >> $GITHUB_OUTPUT
          echo "license=$(node -p "require('./package.json').license")" >> $GITHUB_OUTPUT

  publish-release:
    needs: setup
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      BIN_PATH: ${{ needs.setup.outputs.name }}-bin
      DESCRIPTION: ${{ needs.setup.outputs.description }}
      LICENSE: ${{ needs.setup.outputs.license }}
      DEB_PKG_NAME: ${{ needs.setup.outputs.name }}_${{ needs.setup.outputs.version }}_amd64.deb
      DEB_PKG_RENAMED: clippy-1.2.1-x86_64.deb
      ARCH_PKG_NAME: clippy-bin-1.2.1-1-x86_64.pkg.tar.zst
      RPM_PKG_NAME: clippy-1.2.1-1.x86_64.rpm
      PACKAGE_VERSION: 1.2.1
      PACKAGE_NAME: clippy
    steps:
      - uses: actions/checkout@v3

      - uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: copy deb package && create PKGBUILD
        run: |
          mkdir ${{ env.BIN_PATH }}
          cp -fr ${{ env.DEB_PKG_NAME }} ${{ env.BIN_PATH }}/${{ env.DEB_PKG_RENAMED }}
          cat <<EOF > ./${{ env.BIN_PATH }}/PKGBUILD
            # Maintainer: ${{ github.repository_owner }} <${{ env.EMAIL }}>
            # Contributor: ${{ github.repository_owner }} <${{ env.EMAIL }}>
            _packager="${{ github.repository_owner }} <${{ env.EMAIL }}>"
            _deb_pkgname=${{ env.PACKAGE_NAME }}
            pkgname=${{ env.BIN_PATH }}
            pkgver=${{ env.PACKAGE_VERSION }}
            md5sums=('$(md5sum ${{ env.DEB_PKG_NAME }} | awk '{print $1}')')
            pkgrel=1
            pkgdesc='${{ env.DESCRIPTION }}'
            arch=('${{ env.ARCH }}')
            url="https://github.com/${{ github.repository }}"
            license=('${{ env.LICENSE }}')
            source=("$url/releases/download/${{ env.PACKAGE_VERSION }}/${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}-${{ env.ARCH }}.deb")

            build() {
                rm control.tar.gz
                tar xvf data.tar.gz
            }

            package() {
                cp -fr usr/ \${pkgdir}
            }
          EOF
          cat ${{ env.BIN_PATH }}/PKGBUILD

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: 2m/arch-pkgbuild-builder@v1.17
        with:
          debug: true
          target: pkgbuild
          pkgname: ${{ env.BIN_PATH }}/

      - name: System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sudo make alien
          alien -r -k --scripts --target=x86_64 ${{ env.DEB_PKG_NAME }}
          ls -a

      - name: Create checksums
        run: |
          md5sum ${{ env.BIN_PATH }}/${{ env.ARCH_PKG_NAME}} > ${{ env.BIN_PATH }}/${{ env.ARCH_PKG_NAME }}.md5sum
          md5sum ${{ env.DEB_PKG_NAME }} > ${{ env.DEB_PKG_NAME }}.md5sum
          md5sum ${{ env.RPM_PKG_NAME }} > ${{ env.RPM_PKG_NAME }}.md5sum

      - name: Upload Arch Linux release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.PACKAGE_VERSION }}
          files: |
            ${{ env.BIN_PATH }}/${{ env.ARCH_PKG_NAME }}
            ${{ env.BIN_PATH }}/${{ env.ARCH_PKG_NAME }}.md5sum
            ${{ env.DEB_PKG_NAME }}
            ${{ env.DEB_PKG_NAME }}.md5sum
            ${{ env.RPM_PKG_NAME }}
            ${{ env.RPM_PKG_NAME }}.md5sum
