name: "publish"

on:
  workflow_dispatch:
  push:
    branches: [main]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  EMAIL: don.cryptus@gmail.com
  ARCH: x86_64
  NAME: clippy
  NAME_BIN: clippy-bin
  VERSION: 1.2.3
  DESCRIPTION: "A clipboard manager for Linux"
  LICENSE: MIT
  DEB_PKG_NAME: clippy_1.2.3_amd64.deb
  DEB_PKG_PATH: ./ # NEEDS TO BE CHANGED DEPENDING WHERE YOUR FILE IS
  DEB_PKG_RENAMED: clippy-1.2.3-x86_64.deb # leave as is it needs to be renamed for the arch build
  ARCH_PKG_NAME: clippy-bin-1.2.3-1-x86_64.pkg.tar.zst
  RPM_PKG_NAME: clippy-1.2.3-1.x86_64.rpm
  FOLDER_NAME: clippy-1.2.3

jobs:
  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: copy deb package && create PKGBUILD
        run: |
          mkdir ${{ env.NAME_BIN }}
          cp -fr ${{ env.DEB_PKG_PATH }}${{ env.DEB_PKG_NAME }} ${{ env.NAME_BIN }}/${{ env.DEB_PKG_RENAMED }}
          cat <<EOF > ./${{ env.NAME_BIN }}/PKGBUILD
            # Maintainer: ${{ github.repository_owner }} <${{ env.EMAIL }}>
            # Contributor: ${{ github.repository_owner }} <${{ env.EMAIL }}>
            _packager="${{ github.repository_owner }} <${{ env.EMAIL }}>"
            _deb_pkgname=${{ env.NAME }}
            pkgname=${{ env.NAME_BIN }}
            pkgver=${{ env.VERSION }}
            md5sums=('$(md5sum ${{ env.NAME_BIN }}/${{ env.DEB_PKG_RENAMED }}  | awk '{print $1}')')
            pkgrel=1
            depends=('libappindicator-gtk3' 'webkit2gtk' 'gtk3', 'xdotool')
            pkgdesc='${{ env.DESCRIPTION }}'
            arch=('${{ env.ARCH }}')
            url="https://github.com/${{ github.repository }}"
            license=('${{ env.LICENSE }}')
            source=("\$url/releases/download/${{ env.VERSION }}/${{ env.DEB_PKG_RENAMED }}")

            build() {
                rm control.tar.gz
                tar xvf data.tar.gz
            }

            package() {
                cp -fr usr/ \${pkgdir}
            }
          EOF
          cat ${{ env.NAME_BIN }}/PKGBUILD
          ls -la ${{ env.NAME_BIN }}

      - name: create arch package
        uses: 2m/arch-pkgbuild-builder@v1.17
        with:
          debug: true
          target: pkgbuild
          pkgname: ${{ env.NAME_BIN }}/
