name: "publish"

on:
  workflow_dispatch:
  push:
    branches: [main]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  BIN_PATH: build-aux/arch/kinesis-tailr-bin
  DEB_PKG_NAME: kinesis-tailr-0.5.7-x86_64.deb
  RPM_PKG_NAME: kinesis-tailr-0.5.7-1.x86_64.rpm
  ARCH_PKG_NAME: kinesis-tailr-bin-0.5.7-1-x86_64.pkg.tar.zst
  PACKAGE_NAME: kinesis-tailr
  PACKAGE_VERSION: 0.5.7

jobs:
  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare arch package metadata
        run: |
          MD5_SUM=$(md5sum ${{ env.BIN_PATH }}/${{ env.DEB_PKG_NAME }} | awk '{print $1}')
          sed -i "1i md5sums=('${MD5_SUM}')\n" ${{ env.BIN_PATH }}/PKGBUILD
          sed -i "1i pkgver=${{ env.PACKAGE_VERSION }}\n" ${{ env.BIN_PATH }}/PKGBUILD

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          debug: true
          target: pkgbuild
          pkgname: build-aux/arch/kinesis-tailr-bin/

      - name: Create arch package checksum file
        run: |
          md5sum build-aux/arch/kinesis-tailr-bin/${ARCH_PKG_NAME} >> build-aux/arch/kinesis-tailr-bin/${ARCH_PKG_NAME}.md5sum

      - name: Upload Arch Linux release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.PACKAGE_VERSION }}
          files: |
            build-aux/arch/kinesis-tailr-bin/${{ env.ARCH_PKG_NAME }}
            build-aux/arch/kinesis-tailr-bin/${{ env.ARCH_PKG_NAME }}.md5sum

      - name: ls & cat
        run: |
          echo ${{ env.BIN_PATH }}
          ls -a -l build-aux/arch/kinesis-tailr-bin/
          echo "----------------------"
          echo "----------------------"
          ls -a 
          echo "----------------------"
          echo "----------------------"
          cat build-aux/arch/kinesis-tailr-bin/PKGBUILD
